Repository Douro-ui/design-system, pull requests merged in 2024-06, with the labels that each got.

#30 chore: bump storybook to v8.1.6
  package.json
  yarn.lock
Labels: security

#31 fix: update theme object
  packages/react/src/context/GlobalStyles.tsx
  packages/react/src/context/ThemeProvider.tsx
  packages/react/src/context/__tests__/ThemeProvider.spec.tsx
  packages/react/src/hooks/DarkMode.tsx
  packages/react/src/hooks/index.ts
  packages/react/src/hooks/useTheme.ts
  packages/react/src/tokens/index.ts
  packages/react/src/tokens/themes/index.ts
  packages/react/src/tokens/themes/theme.constants.ts
  packages/react/src/tokens/themes/theme.ts
  packages/react/src/tokens/themes/theme.types.ts
  packages/react/src/tokens/typography/body.ts
  packages/react/src/tokens/typography/display.ts
  packages/react/src/tokens/typography/heading.ts
  packages/react/src/tokens/typography/index.ts
  packages/react/src/utils/__tests__/deepMerge.spec.tsx
  packages/react/src/utils/deepMerge.ts
Labels: bug

#37 build: add stylelint and few rules [skip ci]
  .stylelintrc.json
  README.md
  package.json
  packages/components/button/src/button.styles.ts
  yarn.lock
Labels: build
