Repository Douro-ui/design-system, pull requests merged in 2024-05, with the labels that each got.

#1 build: add extra publish configs
  .github/workflows/publish.yml
  README.md
  packages/components/button/package.json
  packages/svg-icons/package.json
Labels: build

#2 refactor: reset versions [skip ci]
  .github/workflows/publish.yml
  packages/components/button/CHANGELOG.md
  packages/components/button/package.json
  packages/svg-icons/CHANGELOG.md
  packages/svg-icons/package.json
Labels: refactor

#3 refactor: create a react configs package
  packages/react/README.md
  packages/react/package.json
  packages/react/src/hooks/DarkMode.tsx
  packages/react/src/hooks/index.ts
  packages/react/src/index.ts
  packages/react/tsconfig.json
  packages/react/tsconfig.release.json
  packages/react/vite.config.ts
  yarn.lock
Labels: refactor

#4 build: bump tar version in resolutions
  package.json
  yarn.lock
Labels: build

#6 ci: add git checkout to publish workflow
  .github/workflows/publish.yml
Labels: ci

#8 ci: add no verify to github actions
  package.json
Labels: ci

#9 ci: update workflow
  .github/workflows/publish.yml
  package.json
Labels: ci
